name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build_and_publish:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Build Docker image
      run: |
        docker build . --file Dockerfile --tag nextjs:${{ github.sha }}

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Publish to Docker Hub
      run: |
        docker tag nextjs:${{ github.sha }} ${{ secrets.DOCKERHUB_USERNAME }}/nextjs:${{ github.sha }}
        docker push ${{ secrets.DOCKERHUB_USERNAME }}/nextjs:${{ github.sha }}

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Publish to GitHub Container Registry
      run: |
        docker tag nextjs:${{ github.sha }} ghcr.io/${{ github.repository_owner }}/nextjs:${{ github.sha }}
        docker push ghcr.io/${{ github.repository_owner }}/nextjs:${{ github.sha }}