name: Handle Docker Images

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
  BRANCH_NAME: master
  NAME_CONTAINER: app

jobs:
  clean-registry:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: List Docker images
      run: docker image ls ${{ env.REGISTRY }}/${{ github.actor }}

    - name: Get image tags
      run: |
        tags=$(docker image ls --format "{{.Repository}}:{{.Tag}}" | grep <your-image-name> | sort -r | tail -n +4)
        echo "::set-output name=tags::$tags"

    - name: Delete old images
      run: |
        for tag in ${{ steps.get_tags.outputs.tags }}; do
          docker image rm $tag
        done
      env:
        DOCKER_CLI_EXPERIMENTAL: enabled
