name: Handle Docker Images

on:
  schedule:
    - cron: '0 0 * * *' # Esegui ogni giorno a mezzanotte

jobs:
  clean-registry:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: List Docker images
      run: docker image ls

    - name: Get image tags
      run: |
        tags=$(docker image ls --format "{{.Repository}}:{{.Tag}}" | grep <your-image-name> | sort -r | tail -n +4)
        echo "::set-output name=tags::$tags"

    - name: Delete old images
      run: |
        for tag in ${{ steps.get_tags.outputs.tags }}; do
          docker image rm $tag
        done
      env:
        DOCKER_CLI_EXPERIMENTAL: enabled
